set_property MARK_DEBUG true [get_nets design_1_i/myip_0/m00_axi_lite_aclk]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_awaddr[25]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_araddr[25]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_rdata[30]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_wdata[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_rdata[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_araddr[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_wdata[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_awaddr[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_araddr[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_awaddr[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_wdata[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_rdata[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_awaddr[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_rdata[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_araddr[31]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_wdata[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_awaddr[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_wdata[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_rdata[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_araddr[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_awaddr[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_awaddr[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_araddr[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_wdata[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_rdata[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_wdata[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_awaddr[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_araddr[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_awaddr[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_wdata[27]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_rdata[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_wdata[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_rdata[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_awaddr[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_araddr[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_rdata[31]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_wdata[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_rdata[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_wdata[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_araddr[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_wdata[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_rdata[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_wdata[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_rdata[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_awaddr[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_araddr[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_awaddr[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_wdata[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_rdata[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_araddr[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_wdata[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_awaddr[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_araddr[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_awaddr[24]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_wdata[31]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_rdata[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_rdata[27]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_awaddr[30]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_wdata[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_wdata[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_rdata[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_rdata[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_awaddr[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_araddr[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_wdata[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_rdata[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_wdata[30]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_rdata[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_awaddr[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_araddr[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_awaddr[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_wdata[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_rdata[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_awaddr[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_awaddr[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_araddr[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_awaddr[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_wdata[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_rdata[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_awaddr[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_wdata[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_rdata[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_awaddr[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_araddr[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_awaddr[25]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_wdata[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_rdata[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_wdata[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_rdata[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_awaddr[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_awaddr[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_araddr[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_wdata[25]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_rdata[27]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_rdata[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_awaddr[24]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_araddr[24]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_rdata[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_wdata[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_rdata[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_araddr[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_wdata[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_rdata[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_awaddr[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_awaddr[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_araddr[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_wdata[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_rdata[25]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_awaddr[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_wdata[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_rdata[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_araddr[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_wdata[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_rdata[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_rdata[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_awaddr[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_araddr[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_awaddr[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_wdata[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_rdata[31]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_rdata[25]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_awaddr[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_araddr[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_wdata[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_rdata[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_wdata[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_rdata[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_awaddr[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_araddr[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_wdata[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_wdata[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_rdata[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_wdata[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_rdata[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_awaddr[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_awaddr[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_araddr[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_wdata[24]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_rdata[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_awaddr[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_wdata[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_awaddr[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_awaddr[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_wdata[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_rdata[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_wdata[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_awaddr[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_araddr[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_awaddr[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_wdata[30]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_rdata[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_rdata[30]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_awaddr[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_araddr[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_awaddr[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_wdata[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_rdata[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_wdata[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_awaddr[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_araddr[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_awaddr[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_wdata[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_rdata[30]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_wdata[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_rdata[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_awaddr[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_araddr[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_awaddr[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_wdata[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_rdata[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_awaddr[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_wdata[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_rdata[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_awaddr[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_araddr[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_wdata[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_rdata[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_rdata[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_awaddr[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_araddr[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_wdata[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_rdata[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_awaddr[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_araddr[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_rdata[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_awaddr[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_wdata[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_rdata[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_awaddr[27]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_araddr[27]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_wdata[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_rdata[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_wdata[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_rdata[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_awaddr[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_araddr[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_awaddr[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_wdata[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_rdata[24]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_awaddr[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_awaddr[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_awaddr[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_rdata[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_rdata[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_awaddr[31]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_rdata[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_rdata[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_rdata[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_rdata[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_rdata[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_rdata[31]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_wdata[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_wdata[31]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_wdata[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_wdata[24]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_wdata[27]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_rdata[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_awaddr[31]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_rdata[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_rdata[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_rdata[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_rdata[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_rdata[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_rdata[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_awaddr[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_rdata[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_rdata[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_wdata[25]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_araddr[27]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_araddr[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_wdata[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_rdata[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_rdata[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_rdata[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_rdata[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_wdata[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_araddr[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_araddr[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_araddr[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_rdata[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_araddr[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_araddr[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_araddr[24]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_araddr[25]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_rdata[24]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_araddr[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_araddr[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/s00_axi_lite_araddr[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_araddr[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_rdata[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_araddr[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_rdata[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_araddr[30]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_awaddr[30]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_araddr[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_rdata[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_awaddr[27]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_rdata[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_rdata[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_rdata[24]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_rdata[25]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_rdata[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_araddr[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_rdata[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_rdata[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_rdata[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_rdata[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_rdata[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_rdata[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_awaddr[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_awaddr[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_rdata[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_rdata[27]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_rdata[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_wdata[19]}]
set_property MARK_DEBUG true [get_nets design_1_i/myip_0/m00_axi_lite_arready]
set_property MARK_DEBUG true [get_nets design_1_i/myip_0/m00_axi_lite_arvalid]
set_property MARK_DEBUG true [get_nets design_1_i/myip_0/m00_axi_lite_awready]
set_property MARK_DEBUG true [get_nets design_1_i/myip_0/m00_axi_lite_awvalid]
set_property MARK_DEBUG true [get_nets design_1_i/myip_0/m00_axi_lite_rready]
set_property MARK_DEBUG true [get_nets design_1_i/myip_0/m00_axi_lite_rvalid]
set_property MARK_DEBUG true [get_nets design_1_i/myip_0/m00_axi_lite_wready]
set_property MARK_DEBUG true [get_nets design_1_i/myip_0/m00_axi_lite_wvalid]
set_property MARK_DEBUG true [get_nets design_1_i/myip_0/m01_axi_awready]
set_property MARK_DEBUG true [get_nets design_1_i/myip_0/m01_axi_awvalid]
set_property MARK_DEBUG true [get_nets design_1_i/myip_0/m01_axi_rready]
set_property MARK_DEBUG true [get_nets design_1_i/myip_0/m01_axi_rvalid]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_araddr[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_araddr[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_araddr[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_araddr[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_araddr[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_araddr[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_araddr[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_araddr[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_araddr[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_araddr[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_araddr[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_araddr[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_araddr[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_araddr[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_araddr[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_araddr[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_araddr[30]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_araddr[31]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_awaddr[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_awaddr[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_awaddr[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m00_axi_lite_awaddr[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_wdata[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_wdata[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_wdata[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_0/m01_axi_wdata[11]}]
set_property MARK_DEBUG true [get_nets design_1_i/myip_0/m01_axi_wready]
set_property MARK_DEBUG true [get_nets design_1_i/myip_0/m01_axi_wvalid]
set_property MARK_DEBUG true [get_nets design_1_i/myip_0/s00_axi_lite_arready]
set_property MARK_DEBUG true [get_nets design_1_i/myip_0/s00_axi_lite_arvalid]
set_property MARK_DEBUG true [get_nets design_1_i/myip_0/s00_axi_lite_awready]
set_property MARK_DEBUG true [get_nets design_1_i/myip_0/s00_axi_lite_awvalid]
set_property MARK_DEBUG true [get_nets design_1_i/myip_0/s00_axi_lite_rready]
set_property MARK_DEBUG true [get_nets design_1_i/myip_0/s00_axi_lite_rvalid]
set_property MARK_DEBUG true [get_nets design_1_i/myip_0/s00_axi_lite_wready]
set_property MARK_DEBUG true [get_nets design_1_i/myip_0/s00_axi_lite_wvalid]
set_property MARK_DEBUG true [get_nets design_1_i/myip_0/inst/fft_wrapper_inst/next_out]
set_property MARK_DEBUG true [get_nets design_1_i/myip_0/inst/fft_wrapper_inst/in_fifo_full]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 30 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/myip_0/m00_axi_lite_awaddr[2]} {design_1_i/myip_0/m00_axi_lite_awaddr[3]} {design_1_i/myip_0/m00_axi_lite_awaddr[4]} {design_1_i/myip_0/m00_axi_lite_awaddr[5]} {design_1_i/myip_0/m00_axi_lite_awaddr[6]} {design_1_i/myip_0/m00_axi_lite_awaddr[7]} {design_1_i/myip_0/m00_axi_lite_awaddr[8]} {design_1_i/myip_0/m00_axi_lite_awaddr[9]} {design_1_i/myip_0/m00_axi_lite_awaddr[10]} {design_1_i/myip_0/m00_axi_lite_awaddr[11]} {design_1_i/myip_0/m00_axi_lite_awaddr[12]} {design_1_i/myip_0/m00_axi_lite_awaddr[13]} {design_1_i/myip_0/m00_axi_lite_awaddr[14]} {design_1_i/myip_0/m00_axi_lite_awaddr[15]} {design_1_i/myip_0/m00_axi_lite_awaddr[16]} {design_1_i/myip_0/m00_axi_lite_awaddr[17]} {design_1_i/myip_0/m00_axi_lite_awaddr[18]} {design_1_i/myip_0/m00_axi_lite_awaddr[19]} {design_1_i/myip_0/m00_axi_lite_awaddr[20]} {design_1_i/myip_0/m00_axi_lite_awaddr[21]} {design_1_i/myip_0/m00_axi_lite_awaddr[22]} {design_1_i/myip_0/m00_axi_lite_awaddr[23]} {design_1_i/myip_0/m00_axi_lite_awaddr[24]} {design_1_i/myip_0/m00_axi_lite_awaddr[25]} {design_1_i/myip_0/m00_axi_lite_awaddr[26]} {design_1_i/myip_0/m00_axi_lite_awaddr[27]} {design_1_i/myip_0/m00_axi_lite_awaddr[28]} {design_1_i/myip_0/m00_axi_lite_awaddr[29]} {design_1_i/myip_0/m00_axi_lite_awaddr[30]} {design_1_i/myip_0/m00_axi_lite_awaddr[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 30 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/myip_0/m00_axi_lite_araddr[2]} {design_1_i/myip_0/m00_axi_lite_araddr[3]} {design_1_i/myip_0/m00_axi_lite_araddr[4]} {design_1_i/myip_0/m00_axi_lite_araddr[5]} {design_1_i/myip_0/m00_axi_lite_araddr[6]} {design_1_i/myip_0/m00_axi_lite_araddr[7]} {design_1_i/myip_0/m00_axi_lite_araddr[8]} {design_1_i/myip_0/m00_axi_lite_araddr[9]} {design_1_i/myip_0/m00_axi_lite_araddr[10]} {design_1_i/myip_0/m00_axi_lite_araddr[11]} {design_1_i/myip_0/m00_axi_lite_araddr[12]} {design_1_i/myip_0/m00_axi_lite_araddr[13]} {design_1_i/myip_0/m00_axi_lite_araddr[14]} {design_1_i/myip_0/m00_axi_lite_araddr[15]} {design_1_i/myip_0/m00_axi_lite_araddr[16]} {design_1_i/myip_0/m00_axi_lite_araddr[17]} {design_1_i/myip_0/m00_axi_lite_araddr[18]} {design_1_i/myip_0/m00_axi_lite_araddr[19]} {design_1_i/myip_0/m00_axi_lite_araddr[20]} {design_1_i/myip_0/m00_axi_lite_araddr[21]} {design_1_i/myip_0/m00_axi_lite_araddr[22]} {design_1_i/myip_0/m00_axi_lite_araddr[23]} {design_1_i/myip_0/m00_axi_lite_araddr[24]} {design_1_i/myip_0/m00_axi_lite_araddr[25]} {design_1_i/myip_0/m00_axi_lite_araddr[26]} {design_1_i/myip_0/m00_axi_lite_araddr[27]} {design_1_i/myip_0/m00_axi_lite_araddr[28]} {design_1_i/myip_0/m00_axi_lite_araddr[29]} {design_1_i/myip_0/m00_axi_lite_araddr[30]} {design_1_i/myip_0/m00_axi_lite_araddr[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 3 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/myip_0/m00_axi_lite_wdata[0]} {design_1_i/myip_0/m00_axi_lite_wdata[1]} {design_1_i/myip_0/m00_axi_lite_wdata[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_1_i/myip_0/m00_axi_lite_rdata[0]} {design_1_i/myip_0/m00_axi_lite_rdata[1]} {design_1_i/myip_0/m00_axi_lite_rdata[2]} {design_1_i/myip_0/m00_axi_lite_rdata[3]} {design_1_i/myip_0/m00_axi_lite_rdata[4]} {design_1_i/myip_0/m00_axi_lite_rdata[5]} {design_1_i/myip_0/m00_axi_lite_rdata[6]} {design_1_i/myip_0/m00_axi_lite_rdata[7]} {design_1_i/myip_0/m00_axi_lite_rdata[8]} {design_1_i/myip_0/m00_axi_lite_rdata[9]} {design_1_i/myip_0/m00_axi_lite_rdata[10]} {design_1_i/myip_0/m00_axi_lite_rdata[11]} {design_1_i/myip_0/m00_axi_lite_rdata[12]} {design_1_i/myip_0/m00_axi_lite_rdata[13]} {design_1_i/myip_0/m00_axi_lite_rdata[14]} {design_1_i/myip_0/m00_axi_lite_rdata[15]} {design_1_i/myip_0/m00_axi_lite_rdata[16]} {design_1_i/myip_0/m00_axi_lite_rdata[17]} {design_1_i/myip_0/m00_axi_lite_rdata[18]} {design_1_i/myip_0/m00_axi_lite_rdata[19]} {design_1_i/myip_0/m00_axi_lite_rdata[20]} {design_1_i/myip_0/m00_axi_lite_rdata[21]} {design_1_i/myip_0/m00_axi_lite_rdata[22]} {design_1_i/myip_0/m00_axi_lite_rdata[23]} {design_1_i/myip_0/m00_axi_lite_rdata[24]} {design_1_i/myip_0/m00_axi_lite_rdata[25]} {design_1_i/myip_0/m00_axi_lite_rdata[26]} {design_1_i/myip_0/m00_axi_lite_rdata[27]} {design_1_i/myip_0/m00_axi_lite_rdata[28]} {design_1_i/myip_0/m00_axi_lite_rdata[29]} {design_1_i/myip_0/m00_axi_lite_rdata[30]} {design_1_i/myip_0/m00_axi_lite_rdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {design_1_i/myip_0/m01_axi_araddr[0]} {design_1_i/myip_0/m01_axi_araddr[1]} {design_1_i/myip_0/m01_axi_araddr[2]} {design_1_i/myip_0/m01_axi_araddr[3]} {design_1_i/myip_0/m01_axi_araddr[4]} {design_1_i/myip_0/m01_axi_araddr[5]} {design_1_i/myip_0/m01_axi_araddr[6]} {design_1_i/myip_0/m01_axi_araddr[7]} {design_1_i/myip_0/m01_axi_araddr[8]} {design_1_i/myip_0/m01_axi_araddr[9]} {design_1_i/myip_0/m01_axi_araddr[10]} {design_1_i/myip_0/m01_axi_araddr[11]} {design_1_i/myip_0/m01_axi_araddr[12]} {design_1_i/myip_0/m01_axi_araddr[13]} {design_1_i/myip_0/m01_axi_araddr[14]} {design_1_i/myip_0/m01_axi_araddr[15]} {design_1_i/myip_0/m01_axi_araddr[16]} {design_1_i/myip_0/m01_axi_araddr[17]} {design_1_i/myip_0/m01_axi_araddr[18]} {design_1_i/myip_0/m01_axi_araddr[19]} {design_1_i/myip_0/m01_axi_araddr[20]} {design_1_i/myip_0/m01_axi_araddr[21]} {design_1_i/myip_0/m01_axi_araddr[22]} {design_1_i/myip_0/m01_axi_araddr[23]} {design_1_i/myip_0/m01_axi_araddr[24]} {design_1_i/myip_0/m01_axi_araddr[25]} {design_1_i/myip_0/m01_axi_araddr[26]} {design_1_i/myip_0/m01_axi_araddr[27]} {design_1_i/myip_0/m01_axi_araddr[28]} {design_1_i/myip_0/m01_axi_araddr[29]} {design_1_i/myip_0/m01_axi_araddr[30]} {design_1_i/myip_0/m01_axi_araddr[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 32 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {design_1_i/myip_0/m01_axi_rdata[0]} {design_1_i/myip_0/m01_axi_rdata[1]} {design_1_i/myip_0/m01_axi_rdata[2]} {design_1_i/myip_0/m01_axi_rdata[3]} {design_1_i/myip_0/m01_axi_rdata[4]} {design_1_i/myip_0/m01_axi_rdata[5]} {design_1_i/myip_0/m01_axi_rdata[6]} {design_1_i/myip_0/m01_axi_rdata[7]} {design_1_i/myip_0/m01_axi_rdata[8]} {design_1_i/myip_0/m01_axi_rdata[9]} {design_1_i/myip_0/m01_axi_rdata[10]} {design_1_i/myip_0/m01_axi_rdata[11]} {design_1_i/myip_0/m01_axi_rdata[12]} {design_1_i/myip_0/m01_axi_rdata[13]} {design_1_i/myip_0/m01_axi_rdata[14]} {design_1_i/myip_0/m01_axi_rdata[15]} {design_1_i/myip_0/m01_axi_rdata[16]} {design_1_i/myip_0/m01_axi_rdata[17]} {design_1_i/myip_0/m01_axi_rdata[18]} {design_1_i/myip_0/m01_axi_rdata[19]} {design_1_i/myip_0/m01_axi_rdata[20]} {design_1_i/myip_0/m01_axi_rdata[21]} {design_1_i/myip_0/m01_axi_rdata[22]} {design_1_i/myip_0/m01_axi_rdata[23]} {design_1_i/myip_0/m01_axi_rdata[24]} {design_1_i/myip_0/m01_axi_rdata[25]} {design_1_i/myip_0/m01_axi_rdata[26]} {design_1_i/myip_0/m01_axi_rdata[27]} {design_1_i/myip_0/m01_axi_rdata[28]} {design_1_i/myip_0/m01_axi_rdata[29]} {design_1_i/myip_0/m01_axi_rdata[30]} {design_1_i/myip_0/m01_axi_rdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 32 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {design_1_i/myip_0/m01_axi_awaddr[0]} {design_1_i/myip_0/m01_axi_awaddr[1]} {design_1_i/myip_0/m01_axi_awaddr[2]} {design_1_i/myip_0/m01_axi_awaddr[3]} {design_1_i/myip_0/m01_axi_awaddr[4]} {design_1_i/myip_0/m01_axi_awaddr[5]} {design_1_i/myip_0/m01_axi_awaddr[6]} {design_1_i/myip_0/m01_axi_awaddr[7]} {design_1_i/myip_0/m01_axi_awaddr[8]} {design_1_i/myip_0/m01_axi_awaddr[9]} {design_1_i/myip_0/m01_axi_awaddr[10]} {design_1_i/myip_0/m01_axi_awaddr[11]} {design_1_i/myip_0/m01_axi_awaddr[12]} {design_1_i/myip_0/m01_axi_awaddr[13]} {design_1_i/myip_0/m01_axi_awaddr[14]} {design_1_i/myip_0/m01_axi_awaddr[15]} {design_1_i/myip_0/m01_axi_awaddr[16]} {design_1_i/myip_0/m01_axi_awaddr[17]} {design_1_i/myip_0/m01_axi_awaddr[18]} {design_1_i/myip_0/m01_axi_awaddr[19]} {design_1_i/myip_0/m01_axi_awaddr[20]} {design_1_i/myip_0/m01_axi_awaddr[21]} {design_1_i/myip_0/m01_axi_awaddr[22]} {design_1_i/myip_0/m01_axi_awaddr[23]} {design_1_i/myip_0/m01_axi_awaddr[24]} {design_1_i/myip_0/m01_axi_awaddr[25]} {design_1_i/myip_0/m01_axi_awaddr[26]} {design_1_i/myip_0/m01_axi_awaddr[27]} {design_1_i/myip_0/m01_axi_awaddr[28]} {design_1_i/myip_0/m01_axi_awaddr[29]} {design_1_i/myip_0/m01_axi_awaddr[30]} {design_1_i/myip_0/m01_axi_awaddr[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 32 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {design_1_i/myip_0/m01_axi_wdata[0]} {design_1_i/myip_0/m01_axi_wdata[1]} {design_1_i/myip_0/m01_axi_wdata[2]} {design_1_i/myip_0/m01_axi_wdata[3]} {design_1_i/myip_0/m01_axi_wdata[4]} {design_1_i/myip_0/m01_axi_wdata[5]} {design_1_i/myip_0/m01_axi_wdata[6]} {design_1_i/myip_0/m01_axi_wdata[7]} {design_1_i/myip_0/m01_axi_wdata[8]} {design_1_i/myip_0/m01_axi_wdata[9]} {design_1_i/myip_0/m01_axi_wdata[10]} {design_1_i/myip_0/m01_axi_wdata[11]} {design_1_i/myip_0/m01_axi_wdata[12]} {design_1_i/myip_0/m01_axi_wdata[13]} {design_1_i/myip_0/m01_axi_wdata[14]} {design_1_i/myip_0/m01_axi_wdata[15]} {design_1_i/myip_0/m01_axi_wdata[16]} {design_1_i/myip_0/m01_axi_wdata[17]} {design_1_i/myip_0/m01_axi_wdata[18]} {design_1_i/myip_0/m01_axi_wdata[19]} {design_1_i/myip_0/m01_axi_wdata[20]} {design_1_i/myip_0/m01_axi_wdata[21]} {design_1_i/myip_0/m01_axi_wdata[22]} {design_1_i/myip_0/m01_axi_wdata[23]} {design_1_i/myip_0/m01_axi_wdata[24]} {design_1_i/myip_0/m01_axi_wdata[25]} {design_1_i/myip_0/m01_axi_wdata[26]} {design_1_i/myip_0/m01_axi_wdata[27]} {design_1_i/myip_0/m01_axi_wdata[28]} {design_1_i/myip_0/m01_axi_wdata[29]} {design_1_i/myip_0/m01_axi_wdata[30]} {design_1_i/myip_0/m01_axi_wdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 7 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {design_1_i/myip_0/s00_axi_lite_araddr[0]} {design_1_i/myip_0/s00_axi_lite_araddr[1]} {design_1_i/myip_0/s00_axi_lite_araddr[2]} {design_1_i/myip_0/s00_axi_lite_araddr[3]} {design_1_i/myip_0/s00_axi_lite_araddr[4]} {design_1_i/myip_0/s00_axi_lite_araddr[5]} {design_1_i/myip_0/s00_axi_lite_araddr[6]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 32 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {design_1_i/myip_0/s00_axi_lite_rdata[0]} {design_1_i/myip_0/s00_axi_lite_rdata[1]} {design_1_i/myip_0/s00_axi_lite_rdata[2]} {design_1_i/myip_0/s00_axi_lite_rdata[3]} {design_1_i/myip_0/s00_axi_lite_rdata[4]} {design_1_i/myip_0/s00_axi_lite_rdata[5]} {design_1_i/myip_0/s00_axi_lite_rdata[6]} {design_1_i/myip_0/s00_axi_lite_rdata[7]} {design_1_i/myip_0/s00_axi_lite_rdata[8]} {design_1_i/myip_0/s00_axi_lite_rdata[9]} {design_1_i/myip_0/s00_axi_lite_rdata[10]} {design_1_i/myip_0/s00_axi_lite_rdata[11]} {design_1_i/myip_0/s00_axi_lite_rdata[12]} {design_1_i/myip_0/s00_axi_lite_rdata[13]} {design_1_i/myip_0/s00_axi_lite_rdata[14]} {design_1_i/myip_0/s00_axi_lite_rdata[15]} {design_1_i/myip_0/s00_axi_lite_rdata[16]} {design_1_i/myip_0/s00_axi_lite_rdata[17]} {design_1_i/myip_0/s00_axi_lite_rdata[18]} {design_1_i/myip_0/s00_axi_lite_rdata[19]} {design_1_i/myip_0/s00_axi_lite_rdata[20]} {design_1_i/myip_0/s00_axi_lite_rdata[21]} {design_1_i/myip_0/s00_axi_lite_rdata[22]} {design_1_i/myip_0/s00_axi_lite_rdata[23]} {design_1_i/myip_0/s00_axi_lite_rdata[24]} {design_1_i/myip_0/s00_axi_lite_rdata[25]} {design_1_i/myip_0/s00_axi_lite_rdata[26]} {design_1_i/myip_0/s00_axi_lite_rdata[27]} {design_1_i/myip_0/s00_axi_lite_rdata[28]} {design_1_i/myip_0/s00_axi_lite_rdata[29]} {design_1_i/myip_0/s00_axi_lite_rdata[30]} {design_1_i/myip_0/s00_axi_lite_rdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 7 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {design_1_i/myip_0/s00_axi_lite_awaddr[0]} {design_1_i/myip_0/s00_axi_lite_awaddr[1]} {design_1_i/myip_0/s00_axi_lite_awaddr[2]} {design_1_i/myip_0/s00_axi_lite_awaddr[3]} {design_1_i/myip_0/s00_axi_lite_awaddr[4]} {design_1_i/myip_0/s00_axi_lite_awaddr[5]} {design_1_i/myip_0/s00_axi_lite_awaddr[6]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 32 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {design_1_i/myip_0/s00_axi_lite_wdata[0]} {design_1_i/myip_0/s00_axi_lite_wdata[1]} {design_1_i/myip_0/s00_axi_lite_wdata[2]} {design_1_i/myip_0/s00_axi_lite_wdata[3]} {design_1_i/myip_0/s00_axi_lite_wdata[4]} {design_1_i/myip_0/s00_axi_lite_wdata[5]} {design_1_i/myip_0/s00_axi_lite_wdata[6]} {design_1_i/myip_0/s00_axi_lite_wdata[7]} {design_1_i/myip_0/s00_axi_lite_wdata[8]} {design_1_i/myip_0/s00_axi_lite_wdata[9]} {design_1_i/myip_0/s00_axi_lite_wdata[10]} {design_1_i/myip_0/s00_axi_lite_wdata[11]} {design_1_i/myip_0/s00_axi_lite_wdata[12]} {design_1_i/myip_0/s00_axi_lite_wdata[13]} {design_1_i/myip_0/s00_axi_lite_wdata[14]} {design_1_i/myip_0/s00_axi_lite_wdata[15]} {design_1_i/myip_0/s00_axi_lite_wdata[16]} {design_1_i/myip_0/s00_axi_lite_wdata[17]} {design_1_i/myip_0/s00_axi_lite_wdata[18]} {design_1_i/myip_0/s00_axi_lite_wdata[19]} {design_1_i/myip_0/s00_axi_lite_wdata[20]} {design_1_i/myip_0/s00_axi_lite_wdata[21]} {design_1_i/myip_0/s00_axi_lite_wdata[22]} {design_1_i/myip_0/s00_axi_lite_wdata[23]} {design_1_i/myip_0/s00_axi_lite_wdata[24]} {design_1_i/myip_0/s00_axi_lite_wdata[25]} {design_1_i/myip_0/s00_axi_lite_wdata[26]} {design_1_i/myip_0/s00_axi_lite_wdata[27]} {design_1_i/myip_0/s00_axi_lite_wdata[28]} {design_1_i/myip_0/s00_axi_lite_wdata[29]} {design_1_i/myip_0/s00_axi_lite_wdata[30]} {design_1_i/myip_0/s00_axi_lite_wdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list design_1_i/myip_0/inst/fft_wrapper_inst/in_fifo_full]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list design_1_i/myip_0/m00_axi_lite_arready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list design_1_i/myip_0/m00_axi_lite_arvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list design_1_i/myip_0/m00_axi_lite_awready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list design_1_i/myip_0/m00_axi_lite_awvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list design_1_i/myip_0/m00_axi_lite_rready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list design_1_i/myip_0/m00_axi_lite_rvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list design_1_i/myip_0/m00_axi_lite_wready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list design_1_i/myip_0/m00_axi_lite_wvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property port_width 1 [get_debug_ports u_ila_0/probe21]
connect_debug_port u_ila_0/probe21 [get_nets [list design_1_i/myip_0/m01_axi_awready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property port_width 1 [get_debug_ports u_ila_0/probe22]
connect_debug_port u_ila_0/probe22 [get_nets [list design_1_i/myip_0/m01_axi_awvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property port_width 1 [get_debug_ports u_ila_0/probe23]
connect_debug_port u_ila_0/probe23 [get_nets [list design_1_i/myip_0/m01_axi_rready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property port_width 1 [get_debug_ports u_ila_0/probe24]
connect_debug_port u_ila_0/probe24 [get_nets [list design_1_i/myip_0/m01_axi_rvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property port_width 1 [get_debug_ports u_ila_0/probe25]
connect_debug_port u_ila_0/probe25 [get_nets [list design_1_i/myip_0/m01_axi_wready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property port_width 1 [get_debug_ports u_ila_0/probe26]
connect_debug_port u_ila_0/probe26 [get_nets [list design_1_i/myip_0/m01_axi_wvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
set_property port_width 1 [get_debug_ports u_ila_0/probe27]
connect_debug_port u_ila_0/probe27 [get_nets [list design_1_i/myip_0/inst/fft_wrapper_inst/next_out]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
set_property port_width 1 [get_debug_ports u_ila_0/probe28]
connect_debug_port u_ila_0/probe28 [get_nets [list design_1_i/myip_0/s00_axi_lite_arready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe29]
set_property port_width 1 [get_debug_ports u_ila_0/probe29]
connect_debug_port u_ila_0/probe29 [get_nets [list design_1_i/myip_0/s00_axi_lite_arvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe30]
set_property port_width 1 [get_debug_ports u_ila_0/probe30]
connect_debug_port u_ila_0/probe30 [get_nets [list design_1_i/myip_0/s00_axi_lite_awready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe31]
set_property port_width 1 [get_debug_ports u_ila_0/probe31]
connect_debug_port u_ila_0/probe31 [get_nets [list design_1_i/myip_0/s00_axi_lite_awvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe32]
set_property port_width 1 [get_debug_ports u_ila_0/probe32]
connect_debug_port u_ila_0/probe32 [get_nets [list design_1_i/myip_0/s00_axi_lite_rready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe33]
set_property port_width 1 [get_debug_ports u_ila_0/probe33]
connect_debug_port u_ila_0/probe33 [get_nets [list design_1_i/myip_0/s00_axi_lite_rvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe34]
set_property port_width 1 [get_debug_ports u_ila_0/probe34]
connect_debug_port u_ila_0/probe34 [get_nets [list design_1_i/myip_0/s00_axi_lite_wready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe35]
set_property port_width 1 [get_debug_ports u_ila_0/probe35]
connect_debug_port u_ila_0/probe35 [get_nets [list design_1_i/myip_0/s00_axi_lite_wvalid]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
